version: '3'
services: 
   db:
           image: mysql:8.0.20
           volumes:
                   - db-data:/var/lib/mysql
                   - ./:/docker-entrypoint-initdb.d

           environment:
                   MYSQL_ROOT_PASSWORD: changeme
                   MYSQL_DATABASE: cars
                   MYSQL_USER: car_user
                   MYSQL_PASSWORD: changeme
